name: PostgreSQL service example
on: workflow_dispatch

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:20-bookworm-slim
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      nginx:
        image: nginx
        options: >-
          --health-cmd "curl -f http://localhost/ || exit 1"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 3

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Connect to PostgreSQL
        shell: bash
        run: |
          node client.js
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432

      - name: Connect to Nginx
        shell: bash
        run: |
          curl -f http://nginx
